spring:
  application:
    name: demo-nosql

  data:
    mongodb:
      username: sa
      password: MotDePasseFort123!
      port: 27017
      database: Gestion_Avis
      authentication-database: admin

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.mongodb.driver: WARN

  pattern:
    #console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
    #console: "%n%d{HH:mm:ss} %-5level %logger{36}%n  %msg%n%n"
    #console: "%clr(%d{HH:mm:ss}){faint} %clr(%-5level){green} %clr(%logger{36}){cyan} - %msg%n"
    #console: "%n%d{HH:mm:ss} %-5level %logger{36}%n  %msg%n%n"
    #console: "%n%clr(%d{HH:mm:ss}){faint} %clr(%-5level){green} %clr(%logger{36}){cyan}%n  %msg%n%n"
    console: "%n%clr(%d{HH:mm:ss}){faint} %clr(%-5level){green} %clr(%logger{36}){cyan}%n  %clr(%msg){white}%n%n"